### ISSUE TITLE
need update to 2.10.4

### ISSUE THREAD

**Issue by HuMoran** [ardera/flutter-engine-binaries-for-arm#10]
Hi Hannes Winkler,
    Can you share the engine build script? I can help build the engine when flutter updates. Thank you!

Best wishes to you

**Comment by ardera** [comment]
> Can you share the engine build script? I can help build the engine when flutter updates. Thank you!

I appreciate that you want to help, but I'm not sure that's a good idea. People downloading these binaries trust me that they're safe to use, I'm not sure I can guarantee that when someone else builds them for me.

I can share my build script but the easiest way probably is to use jwinarske's [flutter_embedded](https://github.com/meta-flutter/flutter_embedded)

**Comment by HuMoran** [comment]
Thanks for your reply, I got it.
