### ISSUE TITLE
Please tag the recent version

### ISSUE THREAD

**Issue by eximius313** [ardera/flutter-engine-binaries-for-arm#12]
Dear maintener,

I've noticed, that you are tagging previous version only when the most recent version comes in.
Would it be possible that you always tag the newest version as soon as it's released?

Kind regards

**Comment by eximius313** [comment]
@ardera , since `Flutter 3.3.0` is released now, would you be so kind and make tags for both: previous `engine-binaries 3.0.5` (as you usually do) and for `engine-binaries 3.3.0` as well (as soon as you release engine-binaries for it of course)? 
Thank you in advance

**Comment by ardera** [comment]
Ah, sorry I forgot to reply to this.
Yep I'll add the tags.

Btw, you can already download the new engine binaries here: https://github.com/ardera/flutter_embedded (See releases section)
That repo is gonna replace this one here soon, just need to add an install script for it

**Comment by eximius313** [comment]
Awesome! I'm happy to test it (just need the install script :D)

**Comment by eximius313** [comment]
Ok, I've crafted something like this:

```bash
$ version=3.3.1; wget -q -O- https://github.com/ardera/flutter_embedded/releases/download/${version}/armv8-generic.tar.xz | tar --wildcards -xvJ icudtl.dat flutter_embedder.h libflutter_engine.so.*
```
and then run your script:
https://raw.githubusercontent.com/ardera/flutter-engine-binaries-for-arm/main/install.sh

**Comment by eximius313** [comment]
```
#!/bin/bash

VERSION=${1:-3.3.1}
ENGINE_FOLDER=engine_$VERSION
ARM_VERSION=8

cleanup() {
        echo "Cleaning up..."
        cd ..&&\
        rm -fr $ENGINE_FOLDER
}

if [ `uname -m` == 'aarch64' ]; then export ARM=arm64; else export ARM=arm; fi

echo "Installing Engine version: $VERSION for ARM$ARM_VERSION: $ARM..."

mkdir "$ENGINE_FOLDER" &&\
cd "$_" &&\
(
wget -q -O- https://github.com/ardera/flutter_embedded/releases/download/$VERSION/armv$ARM_VERSION-generic.tar.xz | tar --wildcards -xvJ icudtl.dat flutter_embedder.h libflutter_engine.so.* || { cleanup; exit >
) &&\
cleanup &&\
install ./$ARM/libflutter_engine.so.* ./$ARM/icudtl.dat /usr/lib
install ./flutter_embedder.h /usr/include
echo "Done" || echo "Failed"
```

**Comment by eximius313** [comment]
```bash
#!/bin/bash

VERSION=${1:-3.3.1}
ENGINE_DIR=engine_$VERSION
ARM_VERSION=8

cleanup() {
        echo "Cleaning up..."
        cd ..&&\
        rm -fr "$ENGINE_DIR"
}

if [ `uname -m` == 'aarch64' ]; then export ARM=arm64; else export ARM=arm; fi

echo "Installing Engine version: $VERSION for ARM$ARM_VERSION: $ARM..."

mkdir "$ENGINE_DIR" &&\
cd "$_" &&\
pwd &&\
(
        wget -q -O- https://github.com/ardera/flutter_embedded/releases/download/$VERSION/armv$ARM_VERSION-generic.tar.xz | tar --wildcards -xvJ icudtl.dat flutter_embedder.h libflutter_engine.so.* ||\
                { cleanup; exit 1; }
) &&\
install ./$ARM/libflutter_engine.so.* ./$ARM/icudtl.dat /usr/lib &&\
install ./flutter_embedder.h /usr/include &&\
cleanup &&\
echo "Done" || echo "Failed"
```

**Comment by ardera** [comment]
uploaded 3.3.1 and 3.3.2 now and tagged them

**Comment by eximius313** [comment]
@ardera , thanx!
BTW: I saw that you build `generic 32bit`, `generic 64bit` and `rpi-4  specific`, which is only 32bit. Why not `rpi-4` for 64bit as well? 64bit Raspbian is oficially suported

**Comment by ardera** [comment]
True, I should probably support that as well.
