### ISSUE TITLE
Invalid SDK hash Flutter 3.3.7

### ISSUE THREAD

**Issue by bvoq** [ardera/flutter-engine-binaries-for-arm#14]
Could you update the builds for flutter 3.3.7 by any chance?

**Comment by ardera** [comment]
Should be uploaded once https://github.com/ardera/flutter-ci/actions/runs/3427670277 has completed.

**Comment by bvoq** [comment]
Awesome, thanks :-)

**Comment by ardera** [comment]
- fixed in ec83ce6772fbe2860d58c6fe10b212267c85a1d8

**Comment by ardera** [comment]
btw, these are the binaries for generic armv7 and generic aarch64. If you want faster binaries and you're using a Pi 4, you can use the pi4 artifacts of https://github.com/ardera/flutter-ci/releases (there's no installer for them right now though)
