### ISSUE TITLE
Dart 3

### ISSUE THREAD

**Issue by jtkeyva** [ardera/flutter-engine-binaries-for-arm#18]
Just upgraded to Dart 3 and I'm having issues:
Dart Error: Can't load Kernel binary: Invalid kernel binary format version.

Also, I'm unclear how to tell what version of the Dart SDK i can use. I see in the engine-binaries arm64 directly dart-ske.version shows "5b8936496673a285bf8f37472119bc2afb38a295" but i can't tell what version of dart i need to build for the pi

I'm super confused how to know what flutter version i can use with your download.

As of today, how do i download the proper flutter-engine and what version of flutter/dart do i need for this to work?

Thanks

**Comment by ardera** [comment]
The flutter version to use is in the commit message :)

The latest commit message is [`update engine binaries for flutter 3.7.11`](https://github.com/ardera/flutter-engine-binaries-for-arm/commit/f6246d39d8f272dffb893d0d8e7bbb2ba4304f88), so you still have to use 3.7.11 right now

3.10.0 is building right now, it got stuck on some github actions error in the automatically triggered build: https://github.com/ardera/flutter-ci/actions/runs/4939264827. Should be up in a few mins

**Comment by ardera** [comment]
3.10 is up now: https://github.com/ardera/flutter-engine-binaries-for-arm/commit/1bd59166b80d357a59880e8cb3cdd4234df479fd

**Comment by jtkeyva** [comment]
Thank you, I got it working! Now to try with video :)
