### ISSUE TITLE
Awaiting 3.10.6 engine please

### ISSUE THREAD

**Issue by F1p** [ardera/flutter-engine-binaries-for-arm#19]
Getting invalid SDK error - 
SDK version building application is now 3.10.6, engine still 3.10.5

**Comment by ardera** [comment]
Will be uploaded automatically once https://github.com/ardera/flutter-ci/actions/runs/5543287860 has run through.
In the meantime you can just use the 3.10.5 SDK. (`git checkout 3.10.5` in the flutter SDK directory)

**Comment by F1p** [comment]
Thanks very much for the quick reply
