### ISSUE TITLE
3.19.1 missing

### ISSUE THREAD

**Issue by rimb05** [ardera/flutter-engine-binaries-for-arm#20]
Hi, any chance I could get the 3.19.1 version?  It seems to be missing in the builds.

I would be happy to build it myself if you could please provide the instructions.  I need the ARM version, not ARM64.

Thanks

**Comment by ardera** [comment]
The semantic `3.19.1` versions are the flutter SDK versions, which don't necessarily map one-to-one to engine versions. It's often the case that multiple SDK versions use the same engine.

If there's no release for some specific SDK version, that most probably means you can just use the prior one.
