### ISSUE TITLE
github-actions[bot] didn't update binaries for flutter 3.24.0

### ISSUE THREAD

**Issue by derichsv** [ardera/flutter-engine-binaries-for-arm#21]
As described in the title, the binaries have not been updated for flutter 3.24.0 yet. Is this an issue, or does it just take some more time?

Thanks for the awesome work :)

**Comment by ardera** [comment]
Thanks! Took a bit longer this time, I had to update flutterpi_tool first. They should be there once https://github.com/ardera/flutter-ci/actions/runs/10370104972 runs through

**Comment by ardera** [comment]
updated: https://github.com/ardera/flutter-engine-binaries-for-arm/commit/70120740e0245dc412d7c71c7062f2ea8d6fe25b

**Comment by derichsv** [comment]
Thanks :)
