### ISSUE TITLE
Relese build for flutter 2.2.0

### ISSUE THREAD

**Issue by vinicentus** [ardera/flutter-engine-binaries-for-arm#3]
Can you please build this against the latest flutter engine release, so that it will be compatible with flutter stable 2.2.0 (latest stable).

**Comment by ardera** [comment]
I'm working on it, I've built the binaries already but apparently there were some breaking changes so I'll have to fix up some things in flutter-pi as well

(any app seems to be stuck now after the first frame but touch input still reaches the dart VM so not sure what's going on)

**Comment by ardera** [comment]
it's a bug AFAICT: https://github.com/flutter/flutter/issues/83529

implemented a workaround & uploaded the binaries
