### ISSUE TITLE
Architecture mismatch

### ISSUE THREAD

**Issue by gmmota** [ardera/flutter-engine-binaries-for-arm#6]
my development machine:
   Windows 10 with WSL
   Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
   Framework • revision 77d935af4d (4 weeks ago) • 2021-12-16 08:37:33 -0800
   Engine • revision 890a5fca2e
   Tools • Dart 2.15.1
---------------------------------------------------
raspberrypi
    description: ARMv7 Processor rev 4 (v7l)
    product: Raspberry Pi 3 Model B Plus Rev 1.3
    serial: 00000000bc44d195
    width: 32 bits
    capabilities: smp
------------------------------------------------------
Building and Running flutter-pi with build debug mode: OK

Building and Running flutter-pi with Release/Profile mode:  Error mismatch

tested gen_snapshot_linux_x64_release in git repository in
1) arm/gen_snapshot_linux_x64_release
AND
2) arm64/gen_snapshot_linux_x64_release

both show the error message Architecture mismatch.

console output:
flutter-pi --release /home/pi/triforce_balanca
[keyboard] Could not find "XKBMODEL" property inside "/etc/default/keyboard". Default value will be used.[keyboard] Could not find "XKBLAYOUT" property inside "/etc/default/keyboard". Default value will be used.[keyboard] Could not find "XKBVARIANT" property inside "/etc/default/keyboard". Default value will be used.[keyboard] Could not find "XKBOPTIONS" property inside "/etc/default/keyboard". Default value will be used.[flutter-pi] WARNING: display has non-square pixels. Non-square-pixels are not supported by flutter.
===================================
display mode:
  resolution: 800 x 480
  refresh rate: 60Hz
  physical size: 154mm x 86mm
  flutter device pixel ratio: 1,367054
===================================
EGL information:
  version: 1.4
  vendor: "Mesa Project"
  client extensions: "EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless"
  display extensions: "EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_buffer_age EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_WL_bind_wayland_display "
===================================
OpenGL ES information:
  version: "OpenGL ES 2.0 Mesa 20.3.5"
  shading language version: "OpenGL ES GLSL ES 1.0.16"
  vendor: "Broadcom"
  renderer: "VC4 V3D 2.1"
  extensions: "GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_depth_texture GL_AMD_performance_monitor GL_OES_packed_depth_stencil GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_ANGLE_pack_reverse_row_order GL_EXT_occlusion_query_boolean GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_texture_compression_astc_ldr GL_NV_pixel_buffer_object GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_separate_shader_objects GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_draw_elements_base_vertex GL_EXT_texture_border_clamp GL_KHR_context_flush_control GL_OES_draw_elements_base_vertex GL_OES_texture_border_clamp GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_KHR_parallel_shader_compile GL_MESA_tile_raster_order "
===================================
embedder.cc (787): 'FlutterEngineCreateAOTData' returned 'kInvalidArguments'. Architecture mismatch.
[flutter-pi] Could not load AOT data. FlutterEngineCreateAOTData: Invalid arguments.

**Comment by gmmota** [comment]
ok, problem solved, installed the images correctly.

**Comment by sil-main-coo** [comment]
> Được rồi, vấn đề đã được giải quyết, đã cài đặt hình ảnh đúng cách.

Làm sao để sửa lỗi này bạn?
