### ISSUE TITLE
Flutter 2.10.0?

### ISSUE THREAD

**Issue by SkyDev125** [ardera/flutter-engine-binaries-for-arm#7]
Just wondering if there will be support for this newly released version. or if it will take a lot of time to get to it :P

Thank you a lot for this anyway! <3

**Comment by ardera** [comment]
right, working on it

**Comment by SkyDev125** [comment]
oh wow, okay.
thank you very much!

**Comment by SkyDev125** [comment]
not to bother or anything, specially because we are at a weekend. 
but would there be an ETA for how long it would take? I have no idea how complex upgrading this is. sorry for my lack of understanding :P

(trying to use this in my flutter-pi, making the flutter build bundle on my PC... but since it is 2.10.0, the bundle it generated doesn't work... and for some reason the command "flutter build bundle" on 2.8.1 doesn't work on my project... probably due to some package that is relying on the 2.10.0 upgrade already... idk, I tried to downgrade and it didn't work... so yeah. that's why I'm so curious about how long this might take, so I can try to see if my app works on the raspberry pi with flutter pi <3)

**Comment by ardera** [comment]
It's actually not that complicated (except if something breaks), I just can't use my main PC for anything else while building the binaries

- fixed by 8358952893831b4486ac097abc7a438dd25d251c

**Comment by skygamer125** [comment]
[ERROR:flutter/shell/common/shell.cc(94)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
[ERROR:flutter/runtime/dart_isolate.cc(177)] Could not prepare isolate.
[ERROR:flutter/runtime/runtime_controller.cc(384)] Could not create root isolate.
[ERROR:flutter/shell/common/shell.cc(574)] Could not launch engine with configuration.

I dont know why... but this is happening - when I try to run the bundle of the new version 2.10.0
