### ISSUE TITLE
Sharing build script

### ISSUE THREAD

**Issue by spokV** [ardera/flutter-engine-binaries-for-arm#9]
Hi, Thanks for the support...
Would it be possible to share the engine build process and script?
Is there any "official" google support for an aarch64 engine binaries for non desktop environment?

Best Regards

**Comment by ardera** [comment]
Yep for arm64 you just need to look here: https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment and https://github.com/flutter/flutter/wiki/Compiling-the-engine

Run `flutter/tools/gn --help` for more info.

Only arm (32-bit) is a bit problematic.
